# Generated by Django 6.1 on 2026-09-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customvideomodel_height_customvideomodel_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvideomodel',
            name='dominant_colours',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
