# Generated by Django 6.1 on 2026-09-01 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customvideomodel_dominant_colours'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpage',
            name='page_background_colour',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', message='Use a six-digit hexadecimal colour, for example #abc123.')]),
        ),
    ]
