# Generated by Django 6.1 on 2026-09-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailvideos', '0015_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dominant_colours',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
